# Generated by Django 5.2.3 on 2025-06-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='RoleId',
        ),
    ]
